### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by awluedtke** [lincsanders/fitbit_stats_clock#1]
I like that it looks simple while also showing all the data. Probably my default clock face now. But I am wondering if you could have an alternative face that displays distance in miles?

**Comment by lincsanders** [comment]
Hey man :) thanks for the kind words and trying it out!

Do you have your region set to US? I can just make it display miles instead
based on the location preference 🧐

**Comment by awluedtke** [comment]
Sounds like the better way to do it!

Yep, set to US. Also have my 'Units' in feet/miles.

Thanks!

**Comment by lincsanders** [comment]
Well then, thats just me being lazy and not having built it in from day 1.

Can take a week or so to get the new version approved, but keep an eye out;
its coming! :)

**Comment by awluedtke** [comment]
Alright thanks a bunch. Guess I'll be just have to be familiar with the rest of the world's units for a little bit lol.

**Comment by awluedtke** [comment]
Hello again friend, another thing I came across is that the date is one day ahead (the day itself is correct though) - must be an overseas thing. Perhaps the fix you've chosen to implement on the Unit bug will take care of that though.

Just sharin' - not sure if this was a quick lil personal project or if you'd like for it to be used by the masses

**Comment by lincsanders** [comment]
Fixed both - there's a settings companion for the app now, you can "Use Miles?" there, and the date was me trying to use some of the std lib in JS Date() object, I should have just used a more primitive method that the Fitbit SDK better supports. Update should be there in a week or so!
