### ISSUE TITLE
military needs to be choice not only option

### ISSUE THREAD

**Issue by LJinnovate** [lincsanders/fitbit_stats_clock#11]
Hi I loved this but then based on someone wanting military time, you removed am/pm. I am not military and this was the only watch face I found that kept it simple with all stats. could you please add setting so user can choose between and not force military .Keep up tour great work. thnx

**Comment by lincsanders** [comment]
Hey man! You should be able to change that using the "Time Format" option in the settings already.

Click on your profile picture in the Fitbit app > Select your watch (e.g. Versa 2) > "Clock Faces" > tap the three dots > "Settings" > "Time Format" 

Then you can put it as either 24 hour time or AM/PM. 

Hope that helps, thanks for the kind words! :)
