### ISSUE TITLE
Date

### ISSUE THREAD

**Issue by garyslogan** [lincsanders/fitbit_stats_clock#4]
Did not update the date on 1.1.20. Day is correct but not date. I am in Australia. Is it an issue with time zone?

**Comment by lincsanders** [comment]
I saw that too :( this is a great embarrassment - I tried to use the JS Date.toLocaleDateString() function, but it seems in the Fitbit SDK that doesn't use the proper local time - rather GMT. I've rewritten it now to use the proper ones, fix should be live in a week!

**Comment by garyslogan** [comment]
Ok thanks. I love the simplicity of the watch face. I've installed an
alternate and will try your one again in a week or so. Gary in Oz.
