### ISSUE TITLE
Date order 

### ISSUE THREAD

**Issue by sabby65** [lincsanders/fitbit_stats_clock#6]
Could you change the order of the date to day, month, year?

**Comment by lincsanders** [comment]
I sure can can! It'll be an option in Settings, I just need to build a new version and wait for it to get approved.

**Comment by lincsanders** [comment]
New version is waiting for approval now ;)

**Comment by lincsanders** [comment]
1.0.5 should be live, you can set this preference in the settings for the app now :)

**Comment by sabby65** [comment]
Thanks
