### ISSUE TITLE
Military time 

### ISSUE THREAD

**Issue by mellie8** [lincsanders/fitbit_stats_clock#7]
I love the watch face..but this am/pm is not my favorite thing! My brain is solidly locked into military time! Please help!

**Comment by lincsanders** [comment]
Hmm, right now it uses the default phone preference of 24 hour or AM / PM (or at least it should).

I'll make it an explicit setting in the "Settings" section instead :)

**Comment by lincsanders** [comment]
New version is waiting for approval now ;)

(Thanks for the feedback, glad you like it!)

**Comment by lincsanders** [comment]
1.0.5 should be live, you can set this preference in the settings for the app now :)
